name: ChatGPT Action
description: Send a message to ChatGPT
branding:
  icon: aperture
  color: black
inputs:
  api_base:
    description: API base url
    required: false
    secret: true
    default: https://api.openai.com/v1
  api_key:
    description: API key
    required: true
    secret: true
  message:
    description: Message to send to GPT
    required: true
  prompt:
    description: Prompt for GPT
    required: false
    default: You are a helpful assistant.
  model:
    description: GPT model to use
    required: false
    default: gpt-4o
  temperature:
    description: Temperature for GPT
    required: false
    default: 0.7
runs:
  using: composite
  steps:
    - name: Send message to GPT
      id: send_message
      shell: bash
      run: |
        prompt=$(echo "${{ inputs.prompt }}" | jq -R '@json')
        message=$(echo "${{ inputs.message }}" | jq -R '@json')
        echo "$message"
        body=$(jq -n \
        --arg prompt "$prompt" \
        --arg message "$message" \
        '{
           "model": "${{ inputs.model }}",
           "messages": [{"role": "system", "content": $prompt}, {"role": "user", "content": $message}],
           "temperature": ${{ inputs.temperature }}
         }')
        echo "$body"
        response=$(curl -s -X POST \
        ${{ inputs.api_base }}/chat/completions \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ inputs.api_key }}" \
        -d "$body")

        reply=$(echo "$response" | jq -r '.choices[0].message.content // .error.message')
        echo "REPLY=$reply" >> "$GITHUB_OUTPUT"
