name: Add comment via ChatGPT

on:
  issues:
    types: [opened, edited]

jobs:
  chat:
    if: |-
      ${{
        github.event_name == "opened"
        || (github.event_name == "edited" && github.event.issue.comments <= 1 )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Format Message
        id: format
        shell: bash
        run: |
          body=$(cat <<EOF
          ${{ github.event.issue.body }}
          EOF)
          body=$(sed '/^###/ s|\s/\s.*||' <<< "$body")
          {
            echo 'BODY<<EOF'
            echo "$body"
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - id: chat
        name: Generated comment via ChatGPT
        uses: aahl/chatgpt-action@main
        with:
          api_base: ${{ secrets.CHATGPT_API_BASE }}
          api_key: ${{ secrets.CHATGPT_API_KEY }}
          model: deepseek-v3
          prompt: |
            You are a Github issue assistant, please answer this question.
          message: |
            ${{ github.event.issue.title }}
            ${{ steps.format.outputs.BODY }}

            > 以上为用户提交issue的标题(首行)及内容
            > 必须根据内容中“问题详情”的语种用相应的语种回复，无内容详情时使用标题的语种，不明确时使用英文
            > 如果该issue反馈的是某类设备的问题，检查用户是否提供了设备型号、实体属性和日志，未提供时提醒用户

      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: create-comment
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.chat.outputs.REPLY }}
